-- 
--  REMOVE UM LOGIN CONTA OU GRUPO 
-- REMOVE TODOS OS USERS DE TODAS AS BDS
--



EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''tempdb'') 
BEGIN 
    USE [?]
    PRINT ''?''
	IF DATABASE_PRINCIPAL_ID(''PROD_SRV_PREVCHMSCL'') IS NOT NULL
    BEGIN
	ALTER AUTHORIZATION ON SCHEMA::[PROD_SRV_PREVCHMSCL] TO [dbo]
	   DROP USER IF EXISTS [PROD_SRV_PREVCHMSCL]
    END

END /*IF*/
'
--		 ALTER AUTHORIZATION ON SCHEMA::[usrDW24J] TO [dbo]
use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'PROD_SRV_PREVCHMSCL')
     DROP LOGIN [PROD_SRV_PREVCHMSCL];
GO  
