BACKUP LOG Tfs_Cofidis_2018_Configuration
TO DISK = N'Z:\Azure\KroniAG\UserDBs\TRN Logs\Tfs_Cofidis_2018_Configuration_Log_17062025.trn'
WITH INIT, COMPRESSION, STATS = 10;


USE [Tfs_Cofidis_2018_Configuration]
GO
DBCC SHRINKFILE (N'Tfs_Cofidis_2018_Configuration_log' , 0, TRUNCATEONLY)
GO


BACKUP LOG Tfs_COFIDIS_AUTO_2016
TO DISK = N'Z:\Azure\KroniAG\UserDBs\TRN Logs\Tfs_COFIDIS_AUTO_2016_Log_17062025.trn'
WITH INIT, COMPRESSION, STATS = 10;


USE [Tfs_COFIDIS_AUTO_2016]
GO
DBCC SHRINKFILE (N'Tfs_COFIDIS_AUTO_2016_log' , 0, TRUNCATEONLY)
GO

BACKUP LOG Tfs_COFIDIS_ITFS_CM
TO DISK = N'Z:\Azure\KroniAG\UserDBs\TRN Logs\Tfs_COFIDIS_ITFS_CM_Log_17062025.trn'
WITH INIT, COMPRESSION, STATS = 10;


USE [Tfs_COFIDIS_ITFS_CM]
GO
DBCC SHRINKFILE (N'Tfs_COFIDIS_ITFS_CM_log' , 0, TRUNCATEONLY)
GO

BACKUP LOG Tfs_COFIDIS_PD2017
TO DISK = N'Z:\Azure\KroniAG\UserDBs\TRN Logs\Tfs_COFIDIS_PD2017_Log_17062025.trn'
WITH INIT, COMPRESSION, STATS = 10;


USE [Tfs_COFIDIS_PD2017]
GO
DBCC SHRINKFILE (N'Tfs_COFIDIS_PD2017_log' , 0, TRUNCATEONLY)
GO

BACKUP LOG Tfs_COFIDIS_TFSSC2010
TO DISK = N'Z:\Azure\KroniAG\UserDBs\TRN Logs\TfsVersionControl_Log_17062025.trn'
WITH INIT, COMPRESSION, STATS = 10;


USE [Tfs_COFIDIS_TFSSC2010]
GO
DBCC SHRINKFILE (N'TfsVersionControl_log' , 0, TRUNCATEONLY)
GO

DBCC SHRINKFILE ('TfsVersionControl_log', 0)