BACKUP LOG CobrancasDAH
TO DISK = N'E:\BACKUP\CobrancasDAH_Log_20250509_1731.bak'
WITH INIT, COMPRESSION, STATS = 10;


USE [CobrancasDAH]
GO
DBCC SHRINKFILE (N'CobrancasDAH_Log' , 0, TRUNCATEONLY)
GO
