USE [db_cofidis_dah]
GO
ALTER INDEX [IDX_NumdossierCodtipmovimento] ON [dbo].[Movimento] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, 
STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, 
ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 0 MINUTES, ABORT_AFTER_WAIT = NONE)), ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, MAXDOP=16)
GO

ALTER INDEX [NCIX_EventoExtended_dtcriacao] ON [dbo].[Movimento] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, 
STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, 
ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 0 MINUTES, ABORT_AFTER_WAIT = NONE)), ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, MAXDOP=16)
GO
ALTER INDEX [EventoMovimento_FK] ON [dbo].[Movimento] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, 
STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, 
ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 0 MINUTES, ABORT_AFTER_WAIT = NONE)), ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, MAXDOP=16)
GO
ALTER INDEX [IDX_NumdossierCodtipmovimento] ON [dbo].[Movimento] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, 
STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, 
ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 0 MINUTES, ABORT_AFTER_WAIT = NONE)), ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, MAXDOP=16)
GO
ALTER INDEX [IX__PrestacaoMora_NumDossier_DtMensalidade] ON [dbo].[PrestacaoMora] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, 
STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, 
ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 0 MINUTES, ABORT_AFTER_WAIT = NONE)), ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, MAXDOP=16)
GO
ALTER INDEX [IX_Movimento_77] ON [dbo].[Movimento] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, 
STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, 
ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 0 MINUTES, ABORT_AFTER_WAIT = NONE)), ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, MAXDOP=16)
GO
ALTER INDEX [PK__PrestacaoDetalhe] ON [dbo].[PrestacaoDetalhe] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, 
STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, 
ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 0 MINUTES, ABORT_AFTER_WAIT = NONE)), ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, MAXDOP=16)
GO
ALTER INDEX [PK_MOVIMENTO] ON [dbo].[Movimento] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, 
STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, 
ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 0 MINUTES, ABORT_AFTER_WAIT = NONE)), ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, MAXDOP=16)
GO
--use [db_cofidis_dah]
--go

--ALTER INDEX [NCIX_EventoExtended_dtcriacao] ON [db_cofidis_dah].[dbo].[Movimento] REORGANIZE WITH (LOB_COMPACTION = ON);
--ALTER INDEX [EventoMovimento_FK] ON [db_cofidis_dah].[dbo].[Movimento] REORGANIZE WITH (LOB_COMPACTION = ON);
--ALTER INDEX [IDX_NumdossierCodtipmovimento] ON [db_cofidis_dah].[dbo].[Movimento] REORGANIZE WITH (LOB_COMPACTION = ON);
--ALTER INDEX [IX__PrestacaoMora_NumDossier_DtMensalidade] ON [db_cofidis_dah].[dbo].[PrestacaoMora] REORGANIZE WITH (LOB_COMPACTION = ON);
--ALTER INDEX [IX_Movimento_77] ON [db_cofidis_dah].[dbo].[Movimento] REORGANIZE WITH (LOB_COMPACTION = ON);
--ALTER INDEX [PK__PrestacaoDetalhe] ON [db_cofidis_dah].[dbo].[PrestacaoDetalhe] REORGANIZE WITH (LOB_COMPACTION = ON);
--ALTER INDEX [PK_MOVIMENTO] ON [db_cofidis_dah].[dbo].[Movimento] REORGANIZE WITH (LOB_COMPACTION = ON);


use [db_cofidis_dah_interface_aux]
go

ALTER INDEX [PK_MOVIMENTO] ON [db_cofidis_dah_interface_aux].[dbo].[Movimento] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, 
STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, 
ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 0 MINUTES, ABORT_AFTER_WAIT = NONE)), ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, MAXDOP=16)
GO
--ALTER INDEX [PK_MOVIMENTO] ON [db_cofidis_dah_interface_aux].[dbo].[Movimento] REORGANIZE WITH (LOB_COMPACTION = ON);


use [Interfacesdah]
go
ALTER INDEX PK_COF_U_CtrlSaldosDetalhe ON [Interfacesdah].[dbo].[COF_U_CtrlSaldosDetalhe] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, 
STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, 
ONLINE = ON (WAIT_AT_LOW_PRIORITY (MAX_DURATION = 0 MINUTES, ABORT_AFTER_WAIT = NONE)), ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, MAXDOP=16)
GO
--ALTER INDEX [PK_COF_U_CtrlSaldosDetalhe] ON [Interfacesdah].[dbo].[COF_U_CtrlSaldosDetalhe] REORGANIZE WITH (LOB_COMPACTION = ON);