insert into servicebox.Telemetry_1909 ([Id]
           ,[Source]
           ,[ClientId]
           ,[Method]
           ,[Schema]
           ,[Host]
           ,[Path]
           ,[QueryString]
           ,[Payload]
           ,[Response]
           ,[Headers]
           ,[Data]
           ,[RequestedOn]
           ,[RespondedOn]
           ,[Timestamp]
           ,[Success]
           ,[ErrorMessage]
           ,[CorrelationId]
           ,[Processed]
           ,[UpdatedDate])
select   [Id]
           ,[Source]
           ,[ClientId]
           ,[Method]
           ,[Schema]
           ,[Host]
           ,[Path]
           ,[QueryString]
           ,[Payload]
           ,[Response]
           ,[Headers]
           ,[Data]
           ,[RequestedOn]
           ,[RespondedOn]
           ,[Timestamp]
           ,[Success]
           ,[ErrorMessage]
           ,[CorrelationId]
           ,[Processed]
           ,[UpdatedDate]  from servicebox.Telemetry s
WHERE NOT EXISTS (
    SELECT 1
    FROM servicebox.Telemetry_1909 t
    WHERE t.Id = s.Id
);