/*


Inclui_se as script dos Projecto do Armada 


*/
-- UNMASK Privilegies

GRANT UNMASK TO [COFIDIS2000\GrpDataAnalytics001] ;
GRANT UNMASK TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS];
GRANT UNMASK TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV]; 



grant UNMASK TO [ODBC_Diomedes]
grant UNMASK TO [ODBC_Diomedes_Hades]
grant UNMASK TO [grafana_readonly]
grant UNMASK TO [prod_srv_prevchmnrec]
grant UNMASK TO [PROD_SRV_PREVCHMSCL]
--grant UNMASK TO [VCADMIN]
grant UNMASK TO [prod_insurance_cofidisapi]
grant UNMASK TO [CDM\PIMENTCL];
grant UNMASK TO [COFIDIS2000\SPServices_SRV_PROD] ;
grant UNMASK TO [COFIDIS2000\sps_excel_ds] ;
grant UNMASK TO [COFIDIS2000\sps_ss_excl] ;
grant UNMASK TO [COFIDIS2000\srvscvmm] ;
grant UNMASK TO [COFIDIS2000\SIRINGE$] ;
grant UNMASK TO [cofidis2000\prd_apicontperm] ;
grant UNMASK TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS] ;
grant UNMASK TO [COFIDIS2000\GRP_SQL_SUPORTE_APP] ;
grant UNMASK TO [COFIDIS2000\prod_sql_lnk_dio_pri] ;
grant UNMASK TO [COFIDIS2000\PIRS_SVC_ADMIN] ;
grant UNMASK TO  [COFIDIS2000\prismasas1];
grant UNMASK TO [COFIDIS2000\tfsrelease];

---

-- Deny

-- MASK
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics002] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics003] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics004] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics005] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics006] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics007] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics008] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics009] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics010] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics011] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics012] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics013] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics014] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics015] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics016] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics017] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics018] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics019] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics020] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics021] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics022] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics023] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics024] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics025] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics026] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics027] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics028] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics029] ;
REVOKE UNMASK TO [COFIDIS2000\GrpDataAnalytics030] ;
REVOKE UNMASK TO [COFIDIS2000\GrpSQLRWDiomedesDOCP] ;
REVOKE UNMASK TO [COFIDIS2000\GrpSQLRWDiomedesDICV] ;

REVOKE UNMASK TO [teste1]